//
// dialog.h
//


#define	DEFAULT_DIALOG_ACTIVATE_DIST	300.0f

enum
{
	DIALOG_MESSAGE_NEEDSNAILSHELL = 0,
	DIALOG_MESSAGE_GOTSNAILSHELL,

	DIALOG_MESSAGE_FINDSCARECROWHEAD,
	DIALOG_MESSAGE_PUTSCARECROWHEAD,
	DIALOG_MESSAGE_ATTACHEDSCARECROWHEAD,

	DIALOG_MESSAGE_FINDMARBLE,
	DIALOG_MESSAGE_BOWLMARBLE,
	DIALOG_MESSAGE_DONEBOWLING,

	DIALOG_MESSAGE_CHIPMUNK_MAP4ACORN,
	DIALOG_MESSAGE_CHIPMUNK_CHECKPOINT4ACORN,
	DIALOG_MESSAGE_CHIPMUNK_MOUSETRAP,
	DIALOG_MESSAGE_CHIPMUNK_THANKS,
	DIALOG_MESSAGE_CHIPMUNK_CHECKPOINT,

	DIALOG_MESSAGE_POOLWATER,
	DIALOG_MESSAGE_SMASHBERRIES,
	DIALOG_MESSAGE_SQUISHMORE,
	DIALOG_MESSAGE_SQUISHDONE,

	DIALOG_MESSAGE_DOGHOUSE,

	DIALOG_MESSAGE_GOTFLEAS,
	DIALOG_MESSAGE_GOTTICKS,
	DIALOG_MESSAGE_HAPPYDOG,
	DIALOG_MESSAGE_REMEMBERDOG,

	DIALOG_MESSAGE_PLUMBINGINTRO,

	DIALOG_MESSAGE_SLOTCAR,
	DIALOG_MESSAGE_RESCUEMICE,
	DIALOG_MESSAGE_RESCUEMICE2,
	DIALOG_MESSAGE_MICESAVED,
	DIALOG_MESSAGE_SLOTCARPLAYERWON,
	DIALOG_MESSAGE_SLOTCARTRYAGAIN,

	DIALOG_MESSAGE_DOPUZZLE,
	DIALOG_MESSAGE_DONEPUZZLE,

	DIALOG_MESSAGE_BOMBHILLS,
	DIALOG_MESSAGE_BOMBHILLS2,
	DIALOG_MESSAGE_HILLSDONE,

	DIALOG_MESSAGE_MOTHBALL,
	DIALOG_MESSAGE_SILICONDOOR,
	DIALOG_MESSAGE_GETREDCLOVERS,
	DIALOG_MESSAGE_GOTREDCLOVERS,

	DIALOG_MESSAGE_GOFISHING,
	DIALOG_MESSAGE_MOREFISH,
	DIALOG_MESSAGE_THANKSFISH,
	DIALOG_MESSAGE_GETFOOD,
	DIALOG_MESSAGE_MOREFOOD,
	DIALOG_MESSAGE_THANKSFOOD,

	DIALOG_MESSAGE_GETKINDLING,
	DIALOG_MESSAGE_MOREKINDLING,
	DIALOG_MESSAGE_LIGHTFIRE,
	DIALOG_MESSAGE_ENTERHIVE,
	DIALOG_MESSAGE_BOTTLEKEY,

	DIALOG_MESSAGE_MICEDROWN,
	DIALOG_MESSAGE_THANKSNODROWN,
	DIALOG_MESSAGE_GLIDER,
	DIALOG_MESSAGE_SODACAN,

	MAX_DIALOG_MESSAGES
};



void InitDialogManager(void);


void DoDialogMessage(int messNum, int priority, float duration, OGLPoint3D *fromWhere);
void DrawDialogMessage(const OGLSetupOutputType *setupInfo);


int CharToSprite(char c);
float GetCharSpacing(char c, float spacingScale);
