//
// dialog.h
//


#define	DEFAULT_DIALOG_ACTIVATE_DIST	300.0f

typedef enum SWIFT_ENUM_CLOSED DialogMessage
{
	DIALOG_MESSAGE_NEEDSNAILSHELL SWIFT_NAME(needsnailshell) = 0,
	DIALOG_MESSAGE_GOTSNAILSHELL SWIFT_NAME(gotsnailshell),

	DIALOG_MESSAGE_FINDSCARECROWHEAD SWIFT_NAME(findscarecrowhead),
	DIALOG_MESSAGE_PUTSCARECROWHEAD SWIFT_NAME(putscarecrowhead),
	DIALOG_MESSAGE_ATTACHEDSCARECROWHEAD SWIFT_NAME(attachedscarecrowhead),

	DIALOG_MESSAGE_FINDMARBLE SWIFT_NAME(findmarble),
	DIALOG_MESSAGE_BOWLMARBLE SWIFT_NAME(bowlmarble),
	DIALOG_MESSAGE_DONEBOWLING SWIFT_NAME(donebowling),

	DIALOG_MESSAGE_CHIPMUNK_MAP4ACORN SWIFT_NAME(chipmunkMap4acorn),
	DIALOG_MESSAGE_CHIPMUNK_CHECKPOINT4ACORN SWIFT_NAME(chipmunkCheckpoint4acorn),
	DIALOG_MESSAGE_CHIPMUNK_MOUSETRAP SWIFT_NAME(chipmunkMousetrap),
	DIALOG_MESSAGE_CHIPMUNK_THANKS SWIFT_NAME(chipmunkThanks),
	DIALOG_MESSAGE_CHIPMUNK_CHECKPOINT SWIFT_NAME(chipmunkCheckpoint),

	DIALOG_MESSAGE_POOLWATER SWIFT_NAME(poolwater),
	DIALOG_MESSAGE_SMASHBERRIES SWIFT_NAME(smashberries),
	DIALOG_MESSAGE_SQUISHMORE SWIFT_NAME(squishmore),
	DIALOG_MESSAGE_SQUISHDONE SWIFT_NAME(squishdone),

	DIALOG_MESSAGE_DOGHOUSE SWIFT_NAME(doghouse),

	DIALOG_MESSAGE_GOTFLEAS SWIFT_NAME(gotfleas),
	DIALOG_MESSAGE_GOTTICKS SWIFT_NAME(gotticks),
	DIALOG_MESSAGE_HAPPYDOG SWIFT_NAME(happydog),
	DIALOG_MESSAGE_REMEMBERDOG SWIFT_NAME(rememberdog),

	DIALOG_MESSAGE_PLUMBINGINTRO SWIFT_NAME(plumbingintro),

	DIALOG_MESSAGE_SLOTCAR SWIFT_NAME(slotcar),
	DIALOG_MESSAGE_RESCUEMICE SWIFT_NAME(rescuemice),
	DIALOG_MESSAGE_RESCUEMICE2 SWIFT_NAME(rescuemice2),
	DIALOG_MESSAGE_MICESAVED SWIFT_NAME(micesaved),
	DIALOG_MESSAGE_SLOTCARPLAYERWON SWIFT_NAME(slotcarplayerwon),
	DIALOG_MESSAGE_SLOTCARTRYAGAIN SWIFT_NAME(slotcartryagain),

	DIALOG_MESSAGE_DOPUZZLE SWIFT_NAME(dopuzzle),
	DIALOG_MESSAGE_DONEPUZZLE SWIFT_NAME(donepuzzle),

	DIALOG_MESSAGE_BOMBHILLS SWIFT_NAME(bombhills),
	DIALOG_MESSAGE_BOMBHILLS2 SWIFT_NAME(bombhills2),
	DIALOG_MESSAGE_HILLSDONE SWIFT_NAME(hillsdone),

	DIALOG_MESSAGE_MOTHBALL SWIFT_NAME(mothball),
	DIALOG_MESSAGE_SILICONDOOR SWIFT_NAME(silicondoor),
	DIALOG_MESSAGE_GETREDCLOVERS SWIFT_NAME(getredclovers),
	DIALOG_MESSAGE_GOTREDCLOVERS SWIFT_NAME(gotredclovers),

	DIALOG_MESSAGE_GOFISHING SWIFT_NAME(gofishing),
	DIALOG_MESSAGE_MOREFISH SWIFT_NAME(morefish),
	DIALOG_MESSAGE_THANKSFISH SWIFT_NAME(thanksfish),
	DIALOG_MESSAGE_GETFOOD SWIFT_NAME(getfood),
	DIALOG_MESSAGE_MOREFOOD SWIFT_NAME(morefood),
	DIALOG_MESSAGE_THANKSFOOD SWIFT_NAME(thanksfood),

	DIALOG_MESSAGE_GETKINDLING SWIFT_NAME(getkindling),
	DIALOG_MESSAGE_MOREKINDLING SWIFT_NAME(morekindling),
	DIALOG_MESSAGE_LIGHTFIRE SWIFT_NAME(lightfire),
	DIALOG_MESSAGE_ENTERHIVE SWIFT_NAME(enterhive),
	DIALOG_MESSAGE_BOTTLEKEY SWIFT_NAME(bottlekey),

	DIALOG_MESSAGE_MICEDROWN SWIFT_NAME(micedrown),
	DIALOG_MESSAGE_THANKSNODROWN SWIFT_NAME(thanksnodrown),
	DIALOG_MESSAGE_GLIDER SWIFT_NAME(glider),
	DIALOG_MESSAGE_SODACAN SWIFT_NAME(sodacan),

	MAX_DIALOG_MESSAGES SWIFT_NAME(_count)
} DialogMessage;



void InitDialogManager(void);


void DoDialogMessage(int messNum, int priority, float duration, OGLPoint3D *fromWhere);
void DrawDialogMessage(void);


int CharToSprite(char c);
float GetCharSpacing(char c, float spacingScale);
