// Bridging header for Swift-C interop
// This allows Swift to see all C types declared in the project headers
#include "game.h"
#include "SwiftInternal.h"
#include "MenuInternal.h"
#include "PausedInternal.h"
#include "SplineManagerInternal.h"
#include "SparkleInternal.h"
#include "AnaglyphCalibrationInternal.h"
#include "PlayerRaceInternal.h"
#include "SpritesInternal.h"
#include "EnemyInternal.h"
#include "UIEffectsInternal.h"
#include "WaterInternal.h"
#include "PlayerInternal.h"
#include "PickInternal.h"
#include "LevelIntroInternal.h"
#include "MainMenuInternal.h"
#include "SettingsInternal.h"
